name: CI

on: push

jobs:
  build:
    name: Build plugins
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Aliucord/rollup-plugin-aliucord
          path: rollup-plugin-aliucord

      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm i -g pnpm

      - name: Prepare rollup plugin
        working-directory: ./rollup-plugin-aliucord
        run: |
          pnpm i
          pnpm run build

      - name: Setup dependencies
        run: |
          pnpm i ./rollup-plugin-aliucord

      - name: Build plugin
        run: |
          mkdir dist
          node build.mjs Experiments
